version: '2'
services:
  web:
    build: .
    volumes:
      - .:/game
    ports:
      - "8080:8080"

    command: /bin/bash -c "cd /web && pip3 install -r ./req.txt

  db:
    image: postgres:9.6
    command: postgres